---
- name: WSUS feature installation
  win_feature:
    name: UpdateServices
    state: present
    include_management_tools: True

- name: Create content folder for WSUS
  win_file:
    path: "{{ wsus_content_folder }}"
    state: directory
    